[package]
name = "calculator"
version = "0.19.7"
build = "build.rs"

[build-dependencies.lalrpop]
version = "0.19.7"
features = ["lexer"]

[dependencies]
regex = "1"

[dependencies.lalrpop-util]
version = "0.19.7"
